In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [4]:
df = pd.read_csv("E:\\DATA SCIENCE\\NUMPY-PANDAS\\PANDAS\\STACK OVERFLOW SURVEY SET\\stack-overflow-developer-survey-2019\\survey_results_public.csv")

In [6]:
df1 = df.select_dtypes(include = 'number')

In [7]:
df1.isnull().sum()

Respondent           0
CompTotal        32938
ConvertedComp    33060
WorkWeekHrs      24380
CodeRevHrs       39093
Age               9673
dtype: int64

In [8]:
df1.dropna(inplace = True)

In [9]:
df1.shape

(39390, 6)

In [11]:
df1.drop('Respondent',axis = 1,inplace = True)

In [12]:
df1

       CompTotal  ConvertedComp  WorkWeekHrs  CodeRevHrs   Age
8       138000.0        95179.0        32.00        12.0  23.0
12       90000.0        90000.0        40.00         5.0  28.0
13        4150.0        57060.0        40.00         4.0  31.0
16       90000.0        65277.0        45.00         5.0  29.0
18        9500.0        31140.0         8.00         3.0  31.0
...          ...            ...          ...         ...   ...
88323   180000.0       180000.0        40.00         3.0  23.0
88324   239000.0      2000000.0        45.00         5.0  48.0
88325   130000.0       130000.0        40.00         3.0  26.0
88326     6000.0        82488.0        37.75        10.0  34.0
88328    60000.0        68745.0        39.00        10.0  37.0

[39390 rows x 5 columns]

In [13]:
scaler = StandardScaler()

In [14]:
scaled_df = scaler.fit_transform(df1)

In [15]:
scaled_df

array([[-0.00872741, -0.13099872, -0.265389  ,  1.5080155 , -1.07428002],
       [-0.00872741, -0.14900769, -0.05679178,  0.03824963, -0.44168326],
       [-0.00872741, -0.26355016, -0.05679178, -0.17171693, -0.06212521],
       ...,
       [-0.00872741, -0.00991543, -0.05679178, -0.38168348, -0.69472196],
       [-0.00872741, -0.17512921, -0.11545975,  1.08808239,  0.31743284],
       [-0.00872741, -0.22291784, -0.08286644,  1.08808239,  0.6969909 ]])

In [16]:
df2 = pd.DataFrame(data = scaled_df,columns = df1.columns)

In [18]:
df2

       CompTotal  ConvertedComp  WorkWeekHrs  CodeRevHrs       Age
0      -0.008727      -0.130999    -0.265389    1.508015 -1.074280
1      -0.008727      -0.149008    -0.056792    0.038250 -0.441683
2      -0.008727      -0.263550    -0.056792   -0.171717 -0.062125
3      -0.008727      -0.234977     0.073581    0.038250 -0.315164
4      -0.008727      -0.353682    -0.891181   -0.381683 -0.062125
...          ...            ...          ...         ...       ...
39385  -0.008727       0.163950    -0.056792   -0.381683 -1.074280
39386  -0.008727       6.492648     0.073581    0.038250  2.088704
39387  -0.008727      -0.009915    -0.056792   -0.381683 -0.694722
39388  -0.008727      -0.175129    -0.115460    1.088082  0.317433
39389  -0.008727      -0.222918    -0.082866    1.088082  0.696991

[39390 rows x 5 columns]