In [1]:
import pandas as aju
import numpy as np
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.ensemble import BaggingClassifier,RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
import warnings

In [2]:
warnings.filterwarnings('ignore')

In [3]:
df = aju.read_csv("E:\\DATA SCIENCE\\MACHINE-LEARNING\\ML-BASICS\\DATASETS\\ML_18_Bagging_Diabetes.csv")
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [6]:
df.Outcome.value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [7]:
268/500

0.536

In [8]:
x = df.drop('Outcome',axis = 'columns')
y = df.Outcome

In [9]:
scaler = StandardScaler()
x_scale = scaler.fit_transform(x)
x_scale

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x_scale,y,stratify = y,random_state = 99)

In [11]:
y_train.value_counts()

Outcome
0    375
1    201
Name: count, dtype: int64

In [12]:
201/375

0.536

In [13]:
v = cross_val_score(DecisionTreeClassifier(),x,y,cv = 5)
res = np.average(v)
res

0.7188523894406247

In [14]:
bag = BaggingClassifier(estimator=DecisionTreeClassifier(),
    n_estimators=10,max_samples = 0.8,random_state = 99,oob_score = True)
bag.fit(x_train,y_train)
bag.oob_score_

0.7013888888888888

In [15]:
bag.score(x_test,y_test)

0.7708333333333334

In [16]:
score = cross_val_score(BaggingClassifier(estimator=DecisionTreeClassifier(),
    n_estimators=10,max_samples = 0.8,random_state = 99,oob_score = True),x,y,cv = 5)
score.mean()

0.7500636618283677

In [17]:
score = cross_val_score(RandomForestClassifier(),x,y,cv = 5)
score.mean()

0.7591800356506239

In [18]:
bag_lr = BaggingClassifier(estimator=LogisticRegression(),
    n_estimators=10,max_samples = 0.8,random_state = 99,oob_score = True)
bag.fit(x_train,y_train)
bag.oob_score_

0.7013888888888888

In [ ]:
LR,SVC,RFC,XGB,GB,KNN